name: Check PHP syntax with PHP Parallel Lint

on:
  workflow_call:
    inputs:
      php:
        description: PHP Version to use
        default: 8.2
        required: false
        type: string
      extra-args:
        description: Extra args to pass to PHP Parallel Lint
        default: '.'
        required: false
        type: string
      working-directory:
        description: Working directory for the workflow
        default: .
        required: false
        type: string
      tool-directory:
        description: Directory where the tool is installed
        default: tools/php-lint
        required: false
        type: string

jobs:
  phpcs:
    name: PHP Parallel Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}

      - name: Install HP Parallel Lint
        working-directory: ${{ inputs.working-directory }}
        run: composer upgrade --no-progress --no-scripts --prefer-dist --working-dir=${{ inputs.tool-directory }}

      - name: Run HP Parallel Lint
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.tool-directory }}/vendor/bin/parallel-lint ${{ inputs.extra-args }}
