name: Check for bugs with PHPStan static analysis tool

on:
  workflow_call:
    inputs:
      php:
        description: PHP Version to use
        default: 8.2
        required: false
        type: string
      install-phpunit-bridge:
        description: Installs PHPUnit before running PHPStan
        default: false
        required: false
        type: boolean
      working-directory:
        description: Working directory for the workflow
        default: .
        required: false
        type: string
      tool-directory:
        description: Directory where the tool is installed
        default: tools/phpstan
        required: false
        type: string

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}

      - name: Install Composer dependencies
        working-directory: ${{ inputs.working-directory }}
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Install PHPUnit (simple-phpunit)
        if: ${{ true == inputs.install-phpunit-bridge }}
        working-directory: ${{ inputs.working-directory }}
        run: vendor/bin/simple-phpunit --version

      - name: Install PHPStan
        working-directory: ${{ inputs.working-directory }}
        run: composer upgrade --no-progress --no-scripts --prefer-dist --working-dir=${{ inputs.tool-directory }}

      - name: Run PHPStan
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.tool-directory }}/vendor/bin/phpstan analyse
